### ISSUE TITLE
Exception on Mac when switching to Light Theme

### ISSUE THREAD

**Issue by SamKry** [Dansoftowner/jSystemThemeDetector#36]
## Description

An error occurs when switching back to the light theme under MacOS. The problem is that the string returned by this call is null, which leads to a regex parsing problem:

```java
String appleInterfaceStyle = Foundation.toStringViaUTF8(Foundation.invoke(userDefaults, "objectForKey:", Foundation.nsString("AppleInterfaceStyle")));
``` 
_(MacOSThemeDetector line 85)_

## Steps to reproduce

Run the code on:

> MacBook Pro
> 14", 2021
> macOS 14.2.1

```java
if (OsThemeDetector.isSupported()) {
    final OsThemeDetector detector = OsThemeDetector.getDetector();
    detector.registerListener(isDark -> {
        Platform.runLater(() -> {
            if (isDark) {
                System.out.println("Dark theme detected");
            } else {
                System.out.println("Light theme detected");
            }
        });
    });
}
```

## Error output

```
 ERROR com.jthemedetecor.MacOSThemeDetector - Couldn't execute theme name query with the Os
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
        at com.jthemedetecor.MacOSThemeDetector.isDarkTheme(MacOSThemeDetector.java:96)
        at com.jthemedetecor.MacOSThemeDetector.isDark(MacOSThemeDetector.java:86)
        at com.jthemedetecor.MacOSThemeDetector$1.callback(MacOSThemeDetector.java:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:579)
        at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:610)
```

**Comment by SamKry** [comment]
I just saw that you've already implemented the null check. Can you please create a new maven release? Thanks!

**Comment by Dansoftowner** [comment]
New release is created (3.9).
