### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by stephansann** [Dansoftowner/jSystemThemeDetector#7]
Hi @Dansoftowner 

I found this Exception while using jSystemThemeDetector:

WARNING: JNA: Callback com.jthemedetecor.MacOSThemeDetector$1@460d420f threw the following exception
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2067)
	at com.jthemedetector/com.jthemedetecor.MacOSThemeDetector.notifyListeners(MacOSThemeDetector.java:109)
	at com.jthemedetector/com.jthemedetecor.MacOSThemeDetector$1.callback(MacOSThemeDetector.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.jna@5.6.0/com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
	at com.sun.jna@5.6.0/com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)

Maybe you could have a look at this?

Thanks and best regards
Stephan

**Comment by Dansoftowner** [comment]
Hi @stephansann!

Thanks for reporting this problem.
Check version `3.2`.
If the problem is still present, let me know!

Best regards
Daniel

**Comment by stephansann** [comment]
Sorry, it is still happening:

´´´
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2067)
	at com.jthemedetector/com.jthemedetecor.MacOSThemeDetector.notifyListeners(MacOSThemeDetector.java:115)
	at com.jthemedetector/com.jthemedetecor.MacOSThemeDetector$1.callback(MacOSThemeDetector.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.jna@5.6.0/com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
	at com.sun.jna@5.6.0/com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
´´´

First I thought if I really have the new version, but it's happening in line 115 now (before in 109).

**Comment by Dansoftowner** [comment]
Could you give me the exact situation when it's happening?

**Comment by stephansann** [comment]
I open the system properties of my Mac and I change the appearance from dark to light or the other way around. I happens exactly when I do the switch (every time).

**Comment by Dansoftowner** [comment]
Was this problem present in earlier versions?

**Comment by stephansann** [comment]
Sorry, I cannot tell. Maybe yes, maybe no. Have not seen it before.
If it's important I would have to build it back.
Anyhow since 2.1 only modularity changed and I would guess this rather is the reason.

**Comment by Dansoftowner** [comment]
Yeah, i will put some more logging and hopefully I'll figure it out. The problem is that I don't have a Mac 😅

**Comment by Dansoftowner** [comment]
I think I found out what is the problem. 
I had to look at your code for figuring out.

I found out that the problem is with your code because I built your project on a Windows 10 machine and the issue occured there too.

![screenshot](https://user-images.githubusercontent.com/49782833/115022257-7098c600-9ebd-11eb-856d-5516d5b19796.png)

The problem is that you are modifying the listeners list of the `OsThemeDetector` while that list is iterated at the same time (because it iterates over the listeners when the os theme changes).

The possible solution is to use `Platform.runLater` in the listener.
So instead of doing this:
```java
....
public static void applyTheme(ThemeEnum aTheme, Scene aScene) {

        if (ThemeEnum.AUTO == aTheme) {

            Consumer<Boolean> tmpOsThemeDetectorListener = (aBoolean -> applyCurrentTheme(aScene));
            ....
```

Do this:
```java
....
public static void applyTheme(ThemeEnum aTheme, Scene aScene) {

        if (ThemeEnum.AUTO == aTheme) {

            Consumer<Boolean> tmpOsThemeDetectorListener = (aBoolean -> Platform.runLater(() -> applyCurrentTheme(aScene)));
            ....
```

> Note I copied the code snippet from your `ThemeUtil` class

**Comment by Dansoftowner** [comment]
`Platform.runLater` solves the problem because it executes the given command at some later time on the `JavaFX Application Thread`. 

I tried it in your project and it 100% solves this issue.

Look at the [javadoc](https://openjfx.io/javadoc/16/javafx.graphics/javafx/application/Platform.html) for more detailed information.

**Comment by stephansann** [comment]
Uups - you are right - thanks for finding that out 🙏🏻
I can confirm the problem is gone when using Platform.runLater.

**Comment by stephansann** [comment]
Just saw that I have to refactor this code anyhow. It will lead to multiple redundant listeners 🙈

**Comment by stephansann** [comment]
Okay - a last remark on this.

After giving it a second thought, I wasn't so sure about your Application Thread explanation any more. So I refactored my code and removed the runLater again.

Turns out my recursive code caused the problem. After straighten that out the problem disappeared.

As can be seen here the Thread calling the Listener is anyhow the JavaFX Application Thread:
<img width="1734" alt="Screen Shot 2021-04-16 at 17 03 59" src="https://user-images.githubusercontent.com/9678681/115045322-b1510900-9ed6-11eb-84b4-686ddcec7851.png">

So maybe your new note in the README could also be given a second thought!?

Best regards
Stephan

**Comment by Dansoftowner** [comment]
Yes, on Mac that might be the case because the mac theme detection works with a `callback` approach.
**BUT** on Windows, the detection runs on a background thread and the listeners are also notified from that background thread so `Platform.runLater` is neccessary. 

Because your application is cross-platform you should use `Platform.runLater` to make sure the app works on Windows as well :).

Hope I could explain

**Comment by stephansann** [comment]
Okay - thanks - you got me convinced. runLater it is 😉
